export const properties = [
  {
    id: 1,
    imageUrl: "https://placekitten.com/600/600",
    price: "$450",
    address: "Toronto | 3 weeks ago",
    description: "Super adorable, playful, affectionate pure Ragdoll kittens looking for their forever home These kittens are vet-checked, vaccinated and dewormed.",
    numBedroom: 4,
    numWashrooms: 3,
    livingSpace: "3,000 sq.ft.",
  },
  {
    id: 2,
    imageUrl: "https://placekitten.com/500/500",
    price: "$690",
    address: "Toronto | 1 week ago",
    description: "Super adorable, playful, affectionate pure Ragdoll kittens looking for their forever home These kittens are vet-checked, vaccinated and dewormed.",
    numBedroom: 4,
    numWashrooms: 3,
    livingSpace: "2,410 sq.ft.",
  },
  {
    id: 3,
    imageUrl: "https://placekitten.com/400/400",
    price: "$800",
    address: "Toronto | 3 days ago",
    description: "Super adorable, playful, affectionate pure Ragdoll kittens looking for their forever home These kittens are vet-checked, vaccinated and dewormed.",
    numBedroom: 4,
    numWashrooms: 3,
    livingSpace: "4,450 sq.ft.",
  },
];
